{
  "hash": "807162915f789d1058f813c63ac6063d",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Triaje automático de reclamos financieros\"\nsubtitle: \"Informe de avance I — Exploración y transformación de datos\"\nauthor: \"Equipo capstone\"\ndate: last-modified\ndate-format: \"D [de] MMMM [de] YYYY\"\nlang: es\nbibliography: []\nformat:\n  html:\n    toc: true\n    toc-title: \"Contenido\"\n    toc-depth: 3\n    number-sections: true\n    embed-resources: true\n    theme: cosmo\n    fig-width: 8.5\n    fig-height: 4.2\n    tbl-cap-location: bottom\n    fig-cap-location: bottom\n  typst:\n    toc: true\n    number-sections: true\n    fig-width: 7\n    fig-height: 3.6\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n\n# Resumen ejecutivo {.unnumbered}\n\nEste informe documenta la **exploración y creación de features** del proyecto de triaje\nautomático de reclamos financieros. Esta versión cierra la etapa 2 de CRISP-DM —Comprensión\nde los Datos— con E1-E14 completos y deja iniciada la etapa 3 con el tipado del corpus\ncompleto. E12 y E13 usan clasificadores pequeños como sondas para medir señal y comparar\nrepresentaciones; no son la selección final de modelos, que pertenece al Informe II. El\nmockup web y el agente redactor se describen para fijar el destino de las features, pero no\nforman parte del entregable de este informe.\n\n\n**El dato.** 3,837,184 reclamos del *Consumer Financial Protection Bureau*\n(CFPB) con narrativa escrita por el consumidor, 16 columnas, marzo 2015 – julio 2026.\nTodas las columnas llegan como texto y ocupan **5.12 GB**\nen memoria, de los cuales el 72%\nes la narrativa. De las 3,837,184 filas, solo\n**2,583,683 narrativas son únicas** (67.3%):\ncasi un tercio del corpus son textos repetidos, casi siempre plantillas.\n\n\n\n**Cinco hallazgos que cambian el alcance.**\n\n1. **El objetivo prometido en la propuesta no existe en el dato.** Las diapositivas\n   ofrecían predecir *riesgo de disputa* usando el campo «Disputa del consumidor». Ese\n   campo no está entre las 16 columnas: el CFPB dejó de publicarlo en 2017. El objetivo\n   se redefine como **¿la respuesta final registró algún relief?**, declarado explícitamente\n   como *proxy* y no como prueba de obligación, validez o disputa.\n\n2. **La variable de resultado no es binaria.** `Company response to consumer` tiene seis\n   valores, no dos, y uno de ellos marca casos aún sin resolver. Tratarlos como\n   «no hubo compensación» habría metido ruido dirigido en la etiqueta. La regla caso por\n   caso está en la @sec-targets.\n\n3. **La tasa base se mueve más que cualquier modelo.** La proporción de reclamos con\n   compensación pasa de 20% en 2015 a 11% en 2020, 46% en 2024 y 37% en 2025. Entrenar\n   sobre la historia completa es entrenar sobre un fenómeno que ya no existe: el dataset\n   principal se restringe al régimen **2023-2025**.\n\n4. **2026 es un régimen distinto y hubo que excluirlo del conjunto de prueba.** El volumen\n   cae 61% en un solo mes, la composición por producto se da vuelta y las tres tasas base\n   se invierten a la vez. La explicación fácil —casos aún abiertos— queda descartada por el\n   propio dato. El detalle está en @sec-quiebre; es el hallazgo que más afecta el diseño de\n   la evaluación.\n\n5. **El embedding local no reemplaza a TF-IDF como feature predictiva.** E13 encuentra que\n   R1 solo pierde frente a R0 en T1-T3 y empata T4. La fusión R0+R1 mejora modestamente T1,\n   pero empeora los outcomes y aumenta memoria. R0 queda como representación principal;\n   R1 se conserva para estructura temática y recuperación futura (@sec-e13).\n\n**Avance.** 16 de 20 etapas del pipeline tienen su artefacto producido y verificado (@sec-estado).\n\n\n# Estado del pipeline {#sec-estado}\n\nCada etapa deja un artefacto en `reports/artefactos/`. Este informe lee esos\nartefactos, nunca el dato crudo: por eso se genera en segundos y las secciones se\ncompletan solas a medida que el pipeline avanza. Una etapa sin artefacto aparece\nmarcada como pendiente en su sección correspondiente.\n\n::: {#tbl-estado .cell tbl-cap='Estado de las etapas del pipeline. `listo` significa que el artefacto existe y fue verificado.' execution_count=4}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=4}\n| Etapa   | Fase     | Qué produce                                         | Estado    |\n|:--------|:---------|:----------------------------------------------------|:----------|\n| E1      | EDA      | Perfil de tipos, nulos, cardinalidad y memoria      | listo     |\n| D1b     | Targets  | Regla de etiquetado de T2/T3 caso por caso          | listo     |\n| E2      | EDA      | Volumen por mes y cobertura temporal                | listo     |\n| E3      | EDA      | Deriva de taxonomía: Product / Issue por año        | listo     |\n| E9      | EDA      | Tasa base de los targets por año y por producto     | listo     |\n| E4      | EDA      | Desbalance de clases: Pareto de Product e Issue     | listo     |\n| E5      | EDA      | Duplicados y plantillas de narrativa                | listo     |\n| E6      | EDA      | Narrativa: longitud, densidad de XXXX, PII residual | listo     |\n| E7      | EDA      | Concentración de empresas                           | listo     |\n| E8      | EDA      | Geografía: ZIP-3 y malformados                      | listo     |\n| E11     | EDA      | Sesgo por Tags y State, controlando por producto    | listo     |\n| E12     | EDA      | Piso de señal: TF-IDF + LogReg                      | listo     |\n| E13     | EDA      | ¿Vale un embedding? TF-IDF vs embedding local       | listo     |\n| E14     | EDA      | Estructura latente: UMAP + HDBSCAN                  | listo     |\n| F2      | Pipeline | Tipado y contrato de esquema                        | listo     |\n| F3      | Pipeline | Canonicalización de taxonomía                       | listo     |\n| F4      | Pipeline | Repetidos y splits temporales operacional/purgado   | pendiente |\n| F5      | Pipeline | Matrices F0/R0/R1 y auditoría de fuga               | pendiente |\n| F6      | Modelos  | Métricas de T1-T4 y evaluación por cortes           | pendiente |\n| F7      | Negocio  | Simulación de la bandeja: FIFO vs riesgo            | pendiente |\n:::\n:::\n\n\n# El dato {#sec-dato}\n\n## Perfil de las 16 columnas {#sec-perfil}\n\n\n\n::: {#tbl-tipos .cell tbl-cap='Perfil del dato crudo. `tier` es el contrato de disponibilidad: F0 se conoce al recibir el reclamo, F1 lo declara el formulario, FX solo existe después de que la empresa respondió.' execution_count=6}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Columna                      | Tier   |   Valores únicos |   % nulos |   Largo medio |     MB |\n|:-----------------------------|:-------|-----------------:|----------:|--------------:|-------:|\n| Date received                | F0     |            4,138 |      0    |          10   |   65.9 |\n| Consumer complaint narrative | F0     |        2,583,683 |      0    |        1022.4 | 3770.7 |\n| Company                      | F0     |            6,831 |      0    |          26.5 |  126.3 |\n| ZIP code                     | F0     |            6,938 |      0.01 |           5   |   47.6 |\n| State                        | F0     |               63 |      0.36 |           2   |   37   |\n| Tags                         | F0     |                3 |     90.42 |          14.5 |   34.8 |\n| Product                      | F1     |               21 |      0    |          45.5 |  195.9 |\n| Issue                        | F1     |              173 |      0    |          38.5 |  170   |\n| Sub-product                  | F1     |               85 |      1.36 |          17.8 |   93.6 |\n| Sub-issue                    | F1     |              266 |      8.74 |          40   |  163.3 |\n| Date sent to company         | FX     |            4,120 |      0    |          10   |   65.9 |\n| Company response to consumer | FX     |                6 |      0    |          25.5 |  122.8 |\n| Timely response?             | FX     |                2 |      0    |           3   |   40.2 |\n| Company public response      | FX     |               11 |     46.79 |          93   |  210.7 |\n| Complaint ID                 | ID     |        3,837,184 |      0    |           7.4 |   56.4 |\n| Submitted via                | FUERA  |                1 |      0    |           3   |   40.3 |\n:::\n:::\n\n\nTres lecturas de esta tabla:\n\n- **No hay ninguna variable numérica de origen.** Todas las features numéricas habrá que\n  construirlas desde el texto y las fechas.\n- **`Submitted via` tiene un solo valor** (`Web`) en las 3.8 millones de filas: varianza\n  cero, se elimina.\n- **`Complaint ID` es único en el 100% de las filas**, así que sirve de clave de\n  trazabilidad — y nunca como variable predictora.\n\n## El contrato anti-fuga {#sec-fuga}\n\nLa decisión más importante de toda la fase. Las columnas se separan en tres niveles\nsegún **cuándo se conocen**:\n\n| Tier | Cuándo se conoce | Uso permitido |\n|------|------------------|---------------|\n| **F0** | al recibir el reclamo | variables predictoras de todos los modelos |\n| **F1** | lo declara el formulario del CFPB | *etiqueta* del clasificador de motivo. En la bandeja de un banco este campo no existe, así que no puede ser variable predictora del modelo desplegable |\n| **FX** | solo después de que la empresa respondió | únicamente objetivos y diagnóstico. **Nunca** variable predictora |\n\nUn modelo que use `Timely response?` o `Company response to consumer` para predecir\nriesgo obtendría métricas excelentes y sería inútil: esas columnas no existen en el\nmomento en que hay que priorizar el reclamo. La Fase 5 debe añadir\n`tests/test_no_leakage.py`, una prueba que falle si una columna FX aparece en la matriz de\nvariables; hasta que esa prueba y el artefacto F5 existan, el control está diseñado pero no\nimplementado.\n\n# Los objetivos y su definición {#sec-targets}\n\n## Qué puede pagar el dato\n\n| Necesidad del negocio | Modelo | Objetivo |\n|---|---|---|\n| Clasificar y enrutar el reclamo | T1, multiclase | motivo canónico derivado de `Issue`, usado solo como etiqueta histórica |\n| Priorizar por probabilidad de relief registrado | T2, binaria | la respuesta final registró relief monetario o no monetario |\n| Probabilidad de relief monetario | T3, binaria | la respuesta registró relief monetario; no estima un monto ni costo esperado |\n| Riesgo de respuesta tardía | T4, binaria | la respuesta salió fuera de plazo |\n| Semáforo operativo | regla + T4 | días restantes calculados + riesgo histórico estimado |\n| Borrador de respuesta | agente LangGraph posterior a T1-T4 | revisión humana y evaluación con rúbrica |\n| Causas raíz por producto y mes | agregación, no es un modelo | — |\n\n`Issue` no se conoce al recibir un reclamo: en el histórico supervisa T1 y en producción T1\nlo infiere desde F0. Los cuatro modelos alimentan una bandeja; un LLM separado redacta una\nrecomendación y nunca modifica los scores ni envía texto sin aprobación.\n\n```{mermaid}\nflowchart TD\n    A[Nuevo reclamo F0] --> B[Saneo y features R0/R1]\n    B --> C[T1: motivo y equipo]\n    B --> D[T2: probabilidad de relief]\n    B --> E[T3: probabilidad monetaria]\n    B --> F[T4: riesgo de tardanza]\n    A --> G[Regla de fecha límite]\n    C --> H[Motor de triaje]\n    D --> H\n    E --> H\n    F --> H\n    G --> H\n    H --> I[Prioridad, equipo y semáforo]\n    B --> J[Casos similares y políticas aprobadas]\n    I --> K[Agente LangGraph redacta]\n    J --> K\n    K --> L[Guardrails]\n    L --> M[Revisión humana obligatoria]\n```\n\n## La regla de etiquetado, caso por caso\n\n\n\n::: {#tbl-respuesta .cell tbl-cap='Los seis valores de `Company response to consumer` y su traducción a los objetivos T2 y T3. Dos casos se excluyen del entrenamiento en lugar de codificarse como cero.' execution_count=8}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Valor                           |     Filas |     % | T2 compensó   | T3 monetario   | Lectura                          |\n|:--------------------------------|----------:|------:|:--------------|:---------------|:---------------------------------|\n| Closed with explanation         | 2,548,866 | 66.43 | 0             | 0              | resuelto sin compensar           |\n| Closed with non-monetary relief | 1,175,215 | 30.63 | 1             | 0              | compensación no económica        |\n| Closed with monetary relief     |    98,150 |  2.56 | 1             | 1              | compensación económica           |\n| Untimely response               |    11,092 |  0.29 | 0             | 0              | la empresa no respondió a tiempo |\n| Closed                          |     3,741 |  0.1  | 0             | 0              | categoría heredada, sin detalle  |\n| In progress                     |       111 |  0    | excluir       | excluir        | censura: aún sin resultado       |\n| (nulo)                          |         9 |  0    | excluir       | excluir        | sin etiqueta                     |\n:::\n:::\n\n\nEl caso que importa es **`In progress`**: son reclamos cuyo resultado todavía no se\nconoce. Codificarlos como «no hubo compensación» equivale a afirmar algo que el dato no\ndice, y el error no sería aleatorio — se concentraría en los meses más recientes, que son\njustamente los del conjunto de prueba. Se excluyen, junto con los nulos.\n\n`Untimely response` es distinto: sí es un desenlace, pero es *ausencia de respuesta*, no\nprueba de ausencia de relief. La convención principal lo etiqueta como cero y lo marca con\nun indicador. E12 debe repetir T2 excluyendo `Untimely response` y la categoría heredada\n`Closed`; si cambian materialmente PR-AUC o calibración, el informe reportará ambas\nlecturas en lugar de presentar la convención como verdad observada.\n\n# Cobertura temporal {#sec-temporal}\n\n\n\n::: {#cell-fig-volumen .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Reclamos con narrativa recibidos por mes. El volumen crece de forma sostenida hasta 2025 y cae un 61% de un mes al siguiente en enero de 2026, quedándose después en una meseta baja durante seis meses. Una meseta no es un rezago de publicación.](informe_files/figure-html/fig-volumen-output-1.png){#fig-volumen width=946 height=492}\n:::\n:::\n\n\n\nLa ventana 2023-2025 concentra el **66% de todo el corpus**. Restringir el\nentrenamiento a ese periodo no sacrifica volumen: sacrifica historia que ya no describe\nel fenómeno actual. Lo que sí queda fuera, y por otra razón, es 2026 —ver @sec-quiebre.\n\n\n\n# Deriva de la taxonomía {#sec-deriva}\n\n\n\n::: {#cell-fig-deriva .cell execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![Participación de cada producto en el total del año. Las categorías no son estables: el CFPB renombró la familia de *credit reporting* dos veces, y cada rebautizo aparece aquí como una categoría que nace mientras otra muere.](informe_files/figure-html/fig-deriva-output-1.png){#fig-deriva width=1311 height=863}\n:::\n:::\n\n\nEsta figura es la razón por la que existe una **etapa de canonicalización**: antes de\nentrenar nada hay que traducir las 21 etiquetas crudas de producto a un conjunto estable\nde unas 11, y las 173 de `Issue` a entre 25 y 40. El mapa se revisa a mano, se versiona en\n`configs/taxonomia.yaml`, y una prueba de regresión exige que **cada etiqueta canónica\nexista tanto en entrenamiento como en prueba**.\n\n# Desbalance de clases {#sec-desbalance}\n\n\n\nEl clasificador de motivo (T1) tiene que elegir entre las etiquetas de `Issue`. Antes de\nentrenar nada conviene saber cómo se reparte el volumen entre ellas, porque de eso depende\nqué métrica tiene sentido y cuántas clases sobreviven a la canonicalización.\n\n::: {#cell-fig-pareto .cell execution_count=15}\n\n::: {.cell-output .cell-output-display}\n![Concentración de las etiquetas de `Issue` en el régimen 2023-2025. Arriba, las doce etiquetas más frecuentes. Abajo, cuántas etiquetas hacen falta para cubrir cada fracción del volumen: seis bastan para el 80%, y las 86 restantes se reparten el 19% que queda.](informe_files/figure-html/fig-pareto-output-1.png){#fig-pareto width=1251 height=807}\n:::\n:::\n\n\n::: {#tbl-pareto .cell tbl-cap='Desbalance en los dos niveles de la taxonomía declarada, en el corpus completo y en el régimen que se entrena. `clases <1000` cuenta las etiquetas con tan pocas filas que ninguna métrica por clase es estable.' execution_count=16}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Nivel   | Régimen   |   Clases | Top-1   | Top-10   |   Clases hasta 80% |   Clases <1000 filas |\n|:--------|:----------|---------:|:--------|:---------|-------------------:|---------------------:|\n| Product | histórico |       21 | 43.6%   | 97.1%    |                  4 |                    2 |\n| Product | 2023-2025 |       14 | 66.1%   | 98.8%    |                  3 |                    0 |\n| Issue   | histórico |      173 | 31.4%   | 78.6%    |                 12 |                   84 |\n| Issue   | 2023-2025 |       92 | 36.8%   | 86.9%    |                  6 |                   33 |\n:::\n:::\n\n\nDos consecuencias, y ninguna es cosmética.\n\n**La primera es que la canonicalización tiene menos trabajo del que parecía, pero uno más\ndelicado.** De las 173 etiquetas de `Issue` del corpus histórico, solo **92 existen en\n2023-2025**: 81 pertenecen a taxonomías que el CFPB ya retiró. Agrupar las 173 sería\nconstruir un mapa para clases que nunca van a llegar. El mapa se construye sobre las 92, y\nlas 81 restantes solo importan para el experimento de deriva.\n\n**La segunda es que el desbalance del régimen es peor que el del histórico, no mejor.** La\nclase mayoritaria pasa de 31.4% a 36.8% y bastan seis etiquetas para cubrir el 80% del\nvolumen. Un clasificador que responda siempre «información incorrecta en su reporte»\nacierta más de un tercio de las veces. Ese es el número que cualquier modelo tiene que\nsuperar, y es la razón por la que la métrica de T1 se reporta como **macro-F1** y no como\nexactitud: la exactitud premia justamente a ese modelo inútil.\n\n# La narrativa {#sec-narrativa}\n\n## Cuánto del corpus es texto repetido {#sec-plantillas}\n\n\n\n::: {#cell-fig-plantillas .cell execution_count=18}\n\n::: {.cell-output .cell-output-display}\n![Reparto de los reclamos según cuántas veces se repite su narrativa. En el régimen 2023-2025 solo el 48% de los reclamos tiene un texto que no aparece en ningún otro, y uno de cada cinco pertenece a un grupo de más de 500 copias.](informe_files/figure-html/fig-plantillas-output-1.png){#fig-plantillas width=935 height=535}\n:::\n:::\n\n\n::: {#tbl-plantillas .cell tbl-cap='Las seis narrativas más repetidas del régimen 2023-2025, con su producto dominante. Son cartas modelo de disputa de crédito que circulan en internet; el consumidor las copia, cambia el nombre y las envía.' execution_count=19}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| #   |   Copias | Producto                          | Extracto                                                                                          |\n|:----|---------:|:----------------------------------|:--------------------------------------------------------------------------------------------------|\n| #1  |   30,078 | Credit reporting or other person… | In accordance with the Fair Credit Reporting act. The List of accounts below has violated my fed… |\n| #2  |   22,430 | Credit reporting or other person… | My credit reports are inaccurate. These inaccuracies are causing creditors to deny me credit. Yo… |\n| #3  |   18,312 | Credit reporting or other person… | You have reported inaccurate and unauthorized accounts on my credit report, which is a violation… |\n| #4  |   15,802 | Credit reporting or other person… | Upon reviewing my credit report, I have identified inaccurate accounts that need reporting and c… |\n| #5  |   14,446 | Credit reporting or other person… | The Fair Credit Reporting Act ( 15 U.S. Code 1681 ) says ( 1 ) The banking system is dependent u… |\n| #6  |   12,335 | Credit reporting or other person… | I have not supplied proof under the doctrine of estoppel by silence, Engelhardt V. Gravens ( mo … |\n:::\n:::\n\n\n\n**Qué cambia esto.** En el corpus completo, el 41.4%\nde los reclamos comparte su narrativa con al menos otro; dentro del régimen 2023-2025 la\ncifra sube al **52.5%**. Dentro de esa\nventana, la plantilla más copiada aparece\n30,078 veces, siempre sobre el mismo producto.\n\nUna división aleatoria pondría copias del mismo texto a ambos lados y mediría memorización.\nLos cortes son siempre temporales, pero se reportan dos lecturas: la operacional conserva\nplantillas que reaparecen naturalmente después del corte; la purgada elimina de\nvalidación/test los hashes ya vistos en train y mide generalización a texto nuevo.\n\nUn detalle de método que conviene dejar anotado, porque explica una diferencia con las\ncifras de versiones anteriores del plan. Sobre el texto **tal cual llega**, la proporción\nde filas repetidas es 39.1% y el grupo\nmayor tiene 27,496 copias. Al normalizar\n—colapsar espacios y pasar a minúsculas— esas cifras suben a\n41.4% y\n30,110. La diferencia son copias de la misma\ncarta con distinto espaciado. Como el agrupamiento sirve para impedir fuga, la definición\ncorrecta es la **normalizada**: es la más conservadora de las dos.\n\n\n\n## Qué hay dentro del texto {#sec-contenido}\n\n\n\n::: {#cell-fig-narrativa .cell execution_count=22}\n\n::: {.cell-output .cell-output-display}\n![Izquierda: longitud de la narrativa en caracteres. Dos tercios de los reclamos caben en menos de mil caracteres, pero la cola llega hasta 36 mil. Derecha: reclamos con rastros de datos personales que el enmascarado del CFPB no capturó, por cada cien mil. Las dos magnitudes se grafican por separado porque no comparten unidad ni escala.](informe_files/figure-html/fig-narrativa-output-1.png){#fig-narrativa width=937 height=525}\n:::\n:::\n\n\n::: {#tbl-narrativa .cell tbl-cap='Perfil de la narrativa en el régimen 2023-2025. Los bloques `XXXX` son el enmascarado que aplica el CFPB antes de publicar; el porcentaje de caracteres enmascarados mide cuánto del texto es ruido de anonimización.' execution_count=23}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Indicador                              | Valor               |\n|:---------------------------------------|:--------------------|\n| Longitud media                         | 1,005 caracteres    |\n| Mediana / p90 / p99                    | 661 / 2,068 / 5,874 |\n| Máximo                                 | 35,984              |\n| Reclamos con al menos un bloque `XXXX` | 62.8%               |\n| Bloques `XXXX` por reclamo (media)     | 17.0                |\n| Caracteres enmascarados sobre el total | 6.6%                |\n| Reclamos que mencionan un importe      | 18.5%               |\n| Reclamos con marcas de español         | 0.0019%             |\n:::\n:::\n\n\n\n**Tres lecturas, cada una con una consecuencia.**\n\n*El enmascarado es masivo y hay que tratarlo como una señal, no como ruido.* El\n63% de los reclamos contiene bloques `XXXX` y el 6.6%\nde todos los caracteres del corpus es enmascarado. Un TF-IDF ingenuo convertiría `xxxx` en\nel token más frecuente del vocabulario. La normalización de la Fase 5 lo reemplaza por un\nmarcador único y, en paralelo, **cuenta** los bloques: cuántos datos tuvo que ocultar el\nCFPB es en sí mismo un indicador de qué tan cargado de identificadores viene el reclamo.\n\n*El corpus es monolingüe a efectos prácticos.* Las marcas de español aparecen en el\n0.0019% de los textos.\nNo hace falta un detector de idioma ni un modelo multilingüe; conviene volver a revisarlo\nsi el CFPB empieza a publicar el canal en español.\n\n*Queda PII residual, y eso bloquea el envío de texto a servicios externos.*\n25,335 reclamos del régimen contienen al menos un patrón que el enmascarado no\ncapturó: direcciones de correo, URL, cadenas de seis o más dígitos. Son pocos en\nproporción —menos del 1%— pero no son cero, y basta con que no sean cero. La regla 4 de la\ndecisión D6 se mantiene: **ningún texto sale de la red del proyecto sin un segundo\nenmascarado**, y el nivel R1 local no tiene este problema en absoluto. Conviene tomar la\ncifra como cota superior: una cadena de seis dígitos puede ser un número de cuenta o puede\nser un importe sin enmascarar, y este conteo no los distingue.\n\n\n\n# Contra quién se reclama, y desde dónde {#sec-entidades}\n\n## Concentración de empresas {#sec-empresas}\n\n\n\n::: {#cell-fig-empresas .cell execution_count=26}\n\n::: {.cell-output .cell-output-display}\n![Arriba: porcentaje acumulado de reclamos a medida que se añaden empresas, ordenadas de mayor a menor volumen (eje horizontal logarítmico). Abajo: las diez empresas con más reclamos en el régimen 2023-2025. Tres burós de crédito reúnen el 72% del volumen del periodo que se entrena.](informe_files/figure-html/fig-empresas-output-1.png){#fig-empresas width=1200 height=798}\n:::\n:::\n\n\n::: {#tbl-empresas .cell tbl-cap='Distribución de las empresas por volumen de reclamos en el régimen 2023-2025. Las 2,759 empresas con menos de diez reclamos aportan el 0.3% del volumen: no hay con qué estimarles un efecto propio y van a un bucket común.' execution_count=27}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Reclamos por empresa   |   Empresas |   Reclamos | % del volumen   |\n|:-----------------------|-----------:|-----------:|:----------------|\n| 0-9                    |      2,759 |      7,892 | 0.3%            |\n| 10-99                  |      1,157 |     37,605 | 1.5%            |\n| 100-999                |        350 |    107,692 | 4.3%            |\n| 1 000-9 999            |         87 |    257,139 | 10.2%           |\n| 10 000+                |         18 |  2,113,522 | 83.7%           |\n:::\n:::\n\n\n\n**Dos consecuencias para el modelo.** La primera es de codificación: con 4,371\nempresas en el régimen y un 75% del volumen en las cinco primeras, un *one-hot* es\ninviable y una codificación por frecuencia o por objetivo es obligatoria — calculada solo\ncon datos anteriores al periodo de cada fila, para no filtrar el futuro. La cola larga se\nagrupa en un bucket `OTRA`.\n\nLa segunda es más incómoda y afecta a la interpretación de todo lo que venga después. Si\ntres burós de crédito concentran el 72% de los reclamos del régimen —contra el\n61% del corpus completo—, un modelo de texto puede alcanzar buenas métricas\naprendiendo a reconocer *de qué empresa se habla* en vez de *qué problema se describe*. El\nagrupamiento no supervisado de la etapa E14 tiene que correrse dos veces, con y sin los\nnombres de empresa enmascarados; si los grupos cambian mucho, ese hallazgo vale más que el\nagrupamiento original.\n\n\n\n## Geografía: qué queda del código postal {#sec-geografia}\n\n\n\n::: {#cell-fig-geografia .cell execution_count=30}\n\n::: {.cell-output .cell-output-display}\n![Izquierda: forma del campo `ZIP code` en el régimen 2023-2025. El CFPB enmascara los dos últimos dígitos de los códigos poco poblados y el código entero en algunos casos. Derecha: los doce estados con más reclamos. Los dos paneles están separados porque uno reparte el 100% entre tres categorías y el otro entre sesenta y una.](informe_files/figure-html/fig-geografia-output-1.png){#fig-geografia width=946 height=526}\n:::\n:::\n\n\n::: {#tbl-geografia .cell tbl-cap='Cardinalidad de los campos geográficos en el régimen 2023-2025. El prefijo de tres dígitos es la única unidad geográfica que sobrevive al enmascarado, y baja la cardinalidad de casi siete mil valores a 876.' execution_count=31}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Campo                        |     Filas | % del régimen   | Valores distintos   |\n|:-----------------------------|----------:|:----------------|:--------------------|\n| Reclamos del régimen         | 2,523,850 | 100.00%         | —                   |\n| `ZIP code` no nulo           | 2,523,850 | 100.00%         | 6,935               |\n| Con prefijo ZIP-3 utilizable | 2,483,614 | 98.41%          | 876                 |\n| `State` no nulo              | 2,515,633 | 99.67%          | 61                  |\n:::\n:::\n\n\n\n**La decisión que sale de aquí.** El código postal completo no sirve como variable: el\n20.1% de los reclamos lo trae con los dos últimos dígitos\nenmascarados y el 1.6% no trae nada. Pero el prefijo de tres\ndígitos —el que identifica el área postal— sobrevive en el\n**98.4%** de las filas, y baja la cardinalidad de\n6,935 valores a\n876. La variable geográfica del proyecto es\n**ZIP-3, más un indicador booleano de que el código venía enmascarado**, que es informativo\npor sí mismo: el CFPB enmascara justamente los códigos de áreas poco pobladas.\n\nUna corrección sobre el plan, menor pero conviene dejarla escrita: las 290 filas que el\nplan describía como «malformadas» no lo son. Son **nulos**, y están todos fuera del régimen\n2023-2025 —dentro de la ventana que se entrena, `ZIP code` no tiene ni un nulo. No existe\nningún valor con una forma distinta de las tres de la figura: entre los\n2,523,850 reclamos del régimen, el campo o trae cinco dígitos, o\ntrae tres y dos equis, o trae cinco equis. En el corpus completo el enmascarado afecta al\n22.4% de las filas.\n\n\n\n# Tasas base de los objetivos {#sec-tasas}\n\n\n\n::: {#cell-fig-tasas .cell execution_count=34}\n\n::: {.cell-output .cell-output-display}\n![Tasa base anual de los tres objetivos binarios. Se grafican en paneles separados y no superpuestos porque sus escalas difieren en un orden de magnitud; forzarlos a un eje común aplanaría los dos de abajo hasta volverlos ilegibles.](informe_files/figure-html/fig-tasas-output-1.png){#fig-tasas width=951 height=858}\n:::\n:::\n\n\n::: {#tbl-tasas .cell tbl-cap='Tasas base por año. `censurados` son los reclamos marcados como aún sin resolver, excluidos del cálculo.' execution_count=35}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n|   Año |   Reclamos |   Censurados |   T2 % |   T3 % |   T4 % |\n|------:|-----------:|-------------:|-------:|-------:|-------:|\n|  2015 |     54,723 |            0 |  20.28 |   7.22 |   3.44 |\n|  2016 |     77,766 |            0 |  18.93 |   7.29 |   3.96 |\n|  2017 |    115,311 |            0 |  15.06 |   4.91 |   2.98 |\n|  2018 |    118,393 |            1 |  17.87 |   4.76 |   2.02 |\n|  2019 |    124,843 |            0 |  18.5  |   4.4  |   1.75 |\n|  2020 |    174,297 |            0 |  11.25 |   3.81 |   1.39 |\n|  2021 |    203,570 |            0 |  12.93 |   3.67 |   1.52 |\n|  2022 |    337,273 |            0 |  32.19 |   2.74 |   0.8  |\n|  2023 |    487,410 |            1 |  38.83 |   2.51 |   0.64 |\n|  2024 |    814,384 |            7 |  45.8  |   1.71 |   0.47 |\n|  2025 |  1,222,056 |          110 |  36.8  |   1.24 |   0.87 |\n|  2026 |    107,158 |            1 |  18.27 |   6.62 |   3.52 |\n:::\n:::\n\n\nLas tres series se mueven juntas en 2026 y en la dirección contraria a su tendencia. Eso\nno es ruido de un año incompleto: es el mismo fenómeno visto tres veces, y merece sección\npropia.\n\n::: {#tbl-producto .cell tbl-cap='Tasa base por producto crudo. Las diferencias entre productos son mayores que la señal que cualquier modelo puede extraer del texto, así que toda evaluación se reporta también por producto.' execution_count=36}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Producto                                        |   Reclamos |   T2 % |   T3 % |   T4 % |\n|:------------------------------------------------|-----------:|-------:|-------:|-------:|\n| Credit reporting or other personal consumer re… |  1,671,841 |  47.33 |   0.06 |   0.18 |\n| Credit reporting, credit repair services, or o… |    807,499 |  29.15 |   0.25 |   0.5  |\n| Debt collection                                 |    441,051 |  19.06 |   0.56 |   3.54 |\n| Checking or savings account                     |    186,789 |  20.36 |  14.89 |   0.98 |\n| Mortgage                                        |    146,301 |   6.71 |   3.35 |   1.69 |\n| Credit card                                     |    126,827 |  32.61 |  17.37 |   0.58 |\n| Money transfer, virtual currency, or money ser… |    120,644 |   8.75 |   5.47 |   1.55 |\n| Credit card or prepaid card                     |    108,683 |  30.38 |  18.19 |   1.12 |\n| Student loan                                    |     62,620 |   6.32 |   1.53 |  10.02 |\n| Vehicle loan or lease                           |     53,005 |   9.3  |   3.17 |   1.95 |\n:::\n:::\n\n\n# Sesgo por perfil del consumidor {#sec-sesgo}\n\n\n\nEl dato trae dos campos que describen a quien reclama: `Tags`, que marca si es\n*servicemember* o adulto mayor, y `State`. La pregunta obligatoria antes de poner un\nmodelo a priorizar reclamos es si esos grupos reciben resultados distintos. La respuesta\ncruda es que sí, y es engañosa.\n\nUn reclamo marcado `Older American` termina en compensación monetaria mucho más seguido que\nuno sin etiqueta. Pero los adultos mayores **no reclaman sobre los mismos productos**: solo\nel 21% de sus reclamos son del producto dominante del régimen, contra el 68% del resto. Y\nla tasa de compensación depende sobre todo del producto. Sin estratificar, lo que se mide\nes la mezcla de productos del grupo, no un trato distinto.\n\nLa figura pone las dos cifras lado a lado. La **cruda** es la proporción observada. La\n**ajustada** es la tasa que tendría el grupo si su mezcla de productos fuera la de la\npoblación — estandarización directa, calculada por estrato de producto y reagregada con los\npesos de la población. La distancia entre ambas es la parte del efecto que explica la\ncomposición; lo que sobrevive al ajuste es lo que hay que mirar en serio.\n\n::: {#cell-fig-sesgo-tags .cell execution_count=38}\n\n::: {.cell-output .cell-output-display}\n![Tasa cruda y tasa ajustada por producto para cada grupo de `Tags`, régimen 2023-2025. La línea punteada es la tasa de la población. Ajustar por producto reduce la brecha de compensación monetaria de los adultos mayores de siete veces a dos, pero no la elimina; en el objetivo T2 el ajuste apenas mueve la aguja.](informe_files/figure-html/fig-sesgo-tags-output-1.png){#fig-sesgo-tags width=1046 height=537}\n:::\n:::\n\n\n::: {#tbl-sesgo-tags .cell tbl-cap='Cortes por `Tags` en el régimen 2023-2025. `% producto dominante` es el indicador de mezcla: cuánto pesa en el grupo el producto que domina la población. Es la columna que explica por qué la tasa cruda y la ajustada no coinciden.' execution_count=39}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Grupo                         |   Reclamos | % prod. dominante   | T2 crudo   | T2 ajustado   | T3 crudo   | T3 ajustado   |\n|:------------------------------|-----------:|:--------------------|:-----------|:--------------|:-----------|:--------------|\n| (población)                   |  2,523,850 | 66%                 | 40.09%     | 40.09%        | 1.64%      | 1.64%         |\n| (sin etiqueta)                |  2,347,041 | 68%                 | 41.20%     | 40.55%        | 1.38%      | 1.55%         |\n| Servicemember                 |    120,281 | 43%                 | 26.25%     | 30.98%        | 3.02%      | 1.73%         |\n| Older American                |     43,058 | 21%                 | 23.53%     | 28.30%        | 9.85%      | 3.07%         |\n| Older American, Servicemember |     13,352 | 24%                 | 23.07%     | 28.42%        | 8.04%      | 2.84%         |\n:::\n:::\n\n\n\n**El número que no se puede citar solo.** En el régimen 2023-2025, un reclamo marcado\n`Older American` termina en compensación monetaria el **9.85%** de\nlas veces, contra el **1.38%** de los reclamos sin etiqueta: una\nrazón de 7.1 a 1. Controlando por producto, las tasas pasan a\n3.07% y 1.55%, y la razón cae a\n2.0 a 1. Es decir: **la composición explica alrededor del 82% de la\nbrecha**, pero no toda.\n\nEso deja dos obligaciones, no una.\n\nLa primera es de comunicación: la cifra cruda no puede aparecer en una diapositiva sin su\nversión ajustada al lado. Decir que los adultos mayores reciben siete veces más\ncompensación monetaria es describir su cartera de productos, no el trato que reciben.\n\nLa segunda es que **el residuo no es cero y no se puede archivar**. Después de ajustar,\n`Older American` sigue duplicando la tasa de compensación monetaria y sigue\n12 puntos por debajo en T2. El ajuste por\nproducto crudo es un control grueso: quedan afuera el sub-producto, el motivo y la empresa.\nLa evaluación por cortes de la Fase 6 tiene que reportar métricas por estos grupos de\nforma rutinaria, y un modelo que priorice reclamos no puede usar `Tags` como variable sin\nque alguien decida explícitamente que eso es aceptable.\n\n\n\n::: {#cell-fig-sesgo-estado .cell execution_count=41}\n\n::: {.cell-output .cell-output-display}\n![Lo mismo, para los doce estados con más reclamos. Aquí el ajuste sí cierra casi toda la diferencia: la dispersión entre estados en T2 se reduce a menos de tres puntos, y lo que parecía una brecha geográfica en T3 es en su mayor parte una diferencia en qué productos se reclama en cada estado.](informe_files/figure-html/fig-sesgo-estado-output-1.png){#fig-sesgo-estado width=924 height=604}\n:::\n:::\n\n\n::: {#tbl-sesgo-estado .cell tbl-cap='Cortes por `State` en el régimen 2023-2025, ordenados por volumen. La dispersión que queda después del ajuste es del orden de la décima de punto porcentual: no hay un efecto geográfico grande escondido detrás de la composición.' execution_count=42}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Estado      |   Reclamos | % prod. dominante   | T2 crudo   | T2 ajustado   | T3 crudo   | T3 ajustado   |\n|:------------|-----------:|:--------------------|:-----------|:--------------|:-----------|:--------------|\n| (población) |  2,523,850 | 66%                 | 40.09%     | 40.09%        | 1.64%      | 1.64%         |\n| TX          |    357,157 | 71%                 | 42.48%     | 41.10%        | 0.98%      | 1.42%         |\n| FL          |    313,733 | 70%                 | 42.18%     | 40.55%        | 1.18%      | 1.57%         |\n| CA          |    248,188 | 63%                 | 39.62%     | 40.54%        | 2.60%      | 1.95%         |\n| GA          |    197,682 | 71%                 | 41.00%     | 39.40%        | 0.81%      | 1.28%         |\n| NY          |    143,210 | 65%                 | 40.37%     | 40.49%        | 2.27%      | 1.90%         |\n| IL          |    124,578 | 66%                 | 40.57%     | 40.43%        | 1.21%      | 1.21%         |\n| NC          |     98,934 | 69%                 | 41.25%     | 40.03%        | 1.28%      | 1.61%         |\n| PA          |     91,776 | 64%                 | 40.67%     | 40.55%        | 1.67%      | 1.65%         |\n| NJ          |     79,375 | 66%                 | 40.74%     | 40.39%        | 2.00%      | 1.86%         |\n| MD          |     61,207 | 66%                 | 40.09%     | 40.16%        | 1.55%      | 1.59%         |\n| SC          |     60,248 | 72%                 | 42.41%     | 40.88%        | 0.90%      | 1.37%         |\n| MI          |     59,802 | 63%                 | 37.77%     | 38.58%        | 1.70%      | 1.65%         |\n:::\n:::\n\n\n\nEl contraste con `Tags` es lo interesante. Entre los doce estados más grandes, el rango de\nla tasa T2 pasa de 4.7 puntos porcentuales en crudo a 2.5 después de ajustar, y\nla razón entre el estado con más y el con menos compensación monetaria baja de 3.2\na 1.6. Dicho de otro modo: **la geografía casi no aporta nada por sí misma**, y lo\nque parecía un efecto de estado era la mezcla de productos que se reclama en cada uno.\n\nEsto tiene una consecuencia práctica que ahorra trabajo: no hace falta tratar el estado\ncomo una variable sensible con manejo especial, pero sí conviene dejar el corte en la\nevaluación por si el patrón cambia con los datos nuevos. Y refuerza lo del apartado\nanterior — que el residuo de `Tags` sobreviva al mismo ajuste que borra el de `State` es\nprecisamente lo que lo hace digno de atención.\n\n\n\n# Cierre del EDA y creación de features {#sec-cierre-eda}\n\nE12-E14 cierran la exploración, pero necesitan una preparación mínima reproducible. No se\npueden ejecutar sobre una muestra aleatoria ni diseñar la taxonomía mirando el test. El\norden operativo es:\n\n```{mermaid}\nflowchart TD\n    A[Dato crudo DVC<br/>3.84 M filas] --> B[Tipado completo]\n    B --> C[tipado.parquet<br/>3.84 M filas]\n    A --> D[Muestra experimental<br/>175 k filas]\n    D --> E[R0 TF-IDF]\n    D --> F[R1 MiniLM por hash]\n    E --> G[E12 piso de señal]\n    E --> H[E14 control]\n    F --> I[E14 semántico]\n    E --> J[E13 R0 vs R1]\n    F --> J\n    H --> K[Decisiones de taxonomía y representación]\n    I --> K\n    J --> K\n    C --> L[Canonicalización y splits completos]\n    K --> L\n    L --> M[Features finales sobre el corpus en alcance]\n```\n\nLa muestra sirve para **decidir**; no se convierte en el dataset final. Si R0 gana, TF-IDF se\nreajusta con todo el train completo. Si R1 gana, MiniLM se calcula para todos los hashes\núnicos del corpus en alcance.\n\n## Qué significa deduplicar {#sec-deduplicacion}\n\nDeduplicar aquí **no significa borrar reclamos**. Dos personas pueden copiar una plantilla\ny obtener desenlaces distintos. La narrativa normalizada recibe un `hash_narrativa` para:\n\n1. calcular el embedding una sola vez por texto;\n2. impedir que el clustering esté dominado por miles de copias de una plantilla;\n3. medir cuánto del rendimiento viene de memorizar textos conocidos;\n4. auditar hashes con empresas, productos o targets contradictorios.\n\nSe conservan dos evaluaciones temporales. La **operacional** permite que una plantilla vista\nen train reaparezca después, como puede ocurrir en la bandeja. La de **generalización a\ntexto nuevo** purga de validación/test los hashes ya vistos en train y es la lectura\nanti-memorización. Colapsar un grupo a una fila solo es válido para E14; los modelos de\noutcome conservan las filas si sus desenlaces son eventos distintos.\n\n## E12 — Piso de señal R0 {#sec-e12}\n\nE12 ajustó word+character TF-IDF exclusivamente en train y usó\n`SGDClassifier(loss=\"log_loss\")`. Es una sonda barata, no la selección final. Para evitar\nuna lectura inflada por plantillas repetidas, la tabla principal usa el test 2025-H2\n**purgado de hashes vistos en train**.\n\n| target   | variant                  |     n | prevalence   |   average_precision |   hierarchy_violation_rate |   lift_at_5pct |   macro_f1 |   top_3_accuracy |\n|:---------|:-------------------------|------:|:-------------|--------------------:|---------------------------:|---------------:|-----------:|-----------------:|\n| T1       | issue_raw                | 22551 | —            |            nan      |                   nan      |       nan      |     0.2227 |           0.7631 |\n| T2       | main_all                 | 22545 | 0.3412       |              0.4526 |                   nan      |         1.5822 |   nan      |         nan      |\n| T2       | sensitivity_nonambiguous | 22431 | 0.3430       |              0.4535 |                   nan      |         1.567  |   nan      |         nan      |\n| T3       | cascade                  | 22545 | 0.0167       |              0.2828 |                   nan      |        13.3068 |   nan      |         nan      |\n| T3       | direct                   | 22545 | 0.0167       |              0.3088 |                   nan      |        13.7309 |   nan      |         nan      |\n| T3       | direct_vs_t2             | 22545 | 0.0167       |            nan      |                     0.1106 |       nan      |   nan      |         nan      |\n| T3       | three_class              | 22545 | 0.0167       |              0.3032 |                   nan      |        14.4731 |   nan      |         nan      |\n| T4       | direct                   | 22551 | 0.0087       |              0.0354 |                   nan      |         4.6682 |   nan      |         nan      |\n\n\n**Lectura.** T1 alcanza top-3 de 0.763, aunque el macro-F1 de 0.223 confirma que la\nclasificación fina de `Issue` sigue siendo difícil. T2 apenas cambia al excluir respuestas\nambiguas. T3 directo alcanza PR-AUC 0.309 frente a prevalencia 0.0167, pero viola\n`P(T3) ≤ P(T2)` en 11.1% de los casos: la formulación jerárquica sigue justificada aunque\nla cascada no gane todavía. T4 logra lift 4.67 al revisar el 5% superior, pero su PR-AUC\nabsoluta sigue siendo baja por el desbalance extremo.\n\n## E13 — ¿Aporta R1 local? {#sec-e13}\n\nE13 compara R0, R1 y R0+R1 sobre exactamente las mismas filas, targets, splits, pesos y\n`SGDClassifier`. La lectura principal vuelve a ser test 2025-H2 purgado. Además de la métrica,\nse registran tamaño de artefacto, RAM y latencia; el costo de generar MiniLM no está incluido\nen la inferencia del clasificador y se considera por separado.\n\nPara separar preguntas que suelen confundirse:\n\n- **E12 pregunta si existe señal predictiva** usando R0, un vector disperso de palabras y\n  fragmentos de caracteres ponderados con TF-IDF.\n- **E13 cambia la representación, no el problema:** compara R0 con R1 —un vector denso\n  MiniLM de 384 dimensiones— usando el mismo clasificador para T1-T4.\n- **E14 no predice T1-T4:** usa R1 sin etiquetas para visualizar vecindades y descubrir\n  subtemas que ayuden a diseñar la taxonomía canónica.\n\n| target   | representation   | metric            |   value |   delta_vs_r0 |   artifact_mib |   ram_matrix_mib |   fit_seconds |   inference_ms_per_1000 |\n|:---------|:-----------------|:------------------|--------:|--------------:|---------------:|-----------------:|--------------:|------------------------:|\n| T1       | R0_word_char     | macro_f1          |  0.2227 |        0      |        950.351 |         1579.35  |      298.099  |                116.871  |\n| T1       | R0_word_char     | top_3_accuracy    |  0.7631 |        0      |        950.351 |         1579.35  |      298.099  |                116.871  |\n| T2       | R0_word_char     | average_precision |  0.4526 |        0      |        950.351 |         1579.35  |       10.1521 |                  2.9393 |\n| T3       | R0_word_char     | average_precision |  0.3067 |        0      |        950.351 |         1579.35  |       10.0613 |                  2.9043 |\n| T4       | R0_word_char     | average_precision |  0.0373 |        0      |        950.351 |         1579.35  |        9.1701 |                  2.9028 |\n| T1       | R1_MiniLM        | macro_f1          |  0.2118 |       -0.0109 |        192.391 |          256.348 |       61.4697 |                  1.5848 |\n| T1       | R1_MiniLM        | top_3_accuracy    |  0.7165 |       -0.0466 |        192.391 |          256.348 |       61.4697 |                  1.5848 |\n| T2       | R1_MiniLM        | average_precision |  0.4438 |       -0.0088 |        192.391 |          256.348 |        2.515  |                  0.427  |\n| T3       | R1_MiniLM        | average_precision |  0.2341 |       -0.0725 |        192.391 |          256.348 |        2.388  |                  0.4389 |\n| T4       | R1_MiniLM        | average_precision |  0.0375 |        0.0003 |        192.391 |          256.348 |        2.3641 |                  0.3631 |\n| T1       | R0_plus_R1       | macro_f1          |  0.2278 |        0.005  |       1142.74  |         2092.04  |      388.984  |                128.437  |\n| T1       | R0_plus_R1       | top_3_accuracy    |  0.7804 |        0.0173 |       1142.74  |         2092.04  |      388.984  |                128.437  |\n| T2       | R0_plus_R1       | average_precision |  0.4517 |       -0.0009 |       1142.74  |         2092.04  |       12.095  |                  3.8643 |\n| T3       | R0_plus_R1       | average_precision |  0.2838 |       -0.0229 |       1142.74  |         2092.04  |       12.3801 |                  3.7446 |\n| T4       | R0_plus_R1       | average_precision |  0.0364 |       -0.0008 |       1142.74  |         2092.04  |       12.032  |                  3.6901 |\n\n\n::: {#cell-fig-e13-delta .cell execution_count=46}\n\n::: {.cell-output .cell-output-display}\n![Cambio frente a R0 en el test temporal purgado. Un valor positivo mejora la métrica; uno negativo la empeora.](informe_files/figure-html/fig-e13-delta-output-1.png){#fig-e13-delta width=981 height=434}\n:::\n:::\n\n\n::: {#cell-fig-e13-coste .cell execution_count=47}\n\n::: {.cell-output .cell-output-display}\n![Costo técnico de las representaciones en E13. La latencia corresponde al clasificador T2 y no incluye generar el embedding MiniLM.](informe_files/figure-html/fig-e13-coste-output-1.png){#fig-e13-coste width=1093 height=404}\n:::\n:::\n\n\n**Decisión del gate.** R1 solo es más liviano y rápido para el clasificador, pero pierde\n0.047 en top-3 de T1, 0.009 de PR-AUC en T2 y 0.073 en T3. R0+R1 mejora T1\n(+0.005 macro-F1; +0.017 top-3), pero no mejora T2-T4 y eleva la matriz en RAM de\n1,579 a 2,092 MiB. Para la preparación completa se selecciona **R0 como feature textual\nprincipal**. R1 no se escala todavía al corpus completo: se conserva para E14, búsqueda de\ncasos similares y como challenger futuro específico de T1.\n\n## E14 — Estructura latente {#sec-e14}\n\nE14 se ajustó con **73,512 hashes únicos de train**; ninguna narrativa o etiqueta de\nvalidation, test u OOD participó en las decisiones. El procedimiento reproducible fue:\n\n1. colapsar solo para clustering los 100,000 eventos train por `hash_narrativa`;\n2. mantener Product/Issue como nulos cuando un hash tiene etiquetas contradictorias;\n3. reajustar R0 en train único y ejecutar SVD(100) + KMeans con `k={30,40,50}`;\n4. alinear R1 y ejecutar UMAP(12D) + HDBSCAN con tres semillas;\n5. repetir HDBSCAN con `min_cluster_size={50,100,200}`;\n6. enmascarar aliases conservadores de empresa y volver a ajustar UMAP/HDBSCAN;\n7. describir cada cluster con c-TF-IDF directo, sin LLM ni nombres automáticos.\n\n| run_id                  |   n_clusters |   noise_rate |   silhouette_cosine |   product_hash_coverage |   product_hash_nmi |   product_hash_purity_weighted |   issue_hash_nmi |   issue_hash_purity_weighted |\n|:------------------------|-------------:|-------------:|--------------------:|------------------------:|-------------------:|-------------------------------:|-----------------:|-----------------------------:|\n| r0_kmeans_k40           |           40 |       0      |              0.284  |                  0.9939 |             0.2045 |                         0.6004 |           0.2293 |                       0.4395 |\n| r1_umap_seed42_mcs100   |          122 |       0.3007 |              0.1962 |                  0.6952 |             0.2732 |                         0.6973 |           0.3194 |                       0.5407 |\n| r1_umap_seed43_mcs100   |          121 |       0.3274 |              0.207  |                  0.6686 |             0.2703 |                         0.701  |           0.3203 |                       0.5507 |\n| r1_umap_seed44_mcs100   |          120 |       0.3084 |              0.1933 |                  0.6876 |             0.2749 |                         0.6984 |           0.3207 |                       0.5422 |\n| r1_masked_seed42_mcs100 |          130 |       0.4071 |              0.1884 |                  0.5888 |             0.2542 |                         0.7048 |           0.3156 |                       0.5737 |\n\n\nLa proyección siguiente es una **vista 2D adicional para comunicación**. HDBSCAN no fue\nreajustado aquí: sus clusters siguen proviniendo del UMAP 12D. Reducir 384 dimensiones a dos\ninevitablemente deforma distancias, por lo que la figura permite ver vecindades generales,\nno medir separación ni calidad del modelo.\n\n::: {#cell-fig-e14-umap-cluster .cell execution_count=49}\n\n::: {.cell-output .cell-output-display}\n![UMAP 2D de R1 coloreado por los diez clusters HDBSCAN más grandes. Gris claro reúne clusters menores y gris oscuro representa ruido.](informe_files/figure-html/fig-e14-umap-cluster-output-1.png){#fig-e14-umap-cluster width=918 height=673}\n:::\n:::\n\n\n::: {#cell-fig-e14-umap-producto .cell execution_count=50}\n\n::: {.cell-output .cell-output-display}\n![La misma proyección R1, coloreada por Product como referencia externa. Las dos categorías de reporte crediticio evidencian deriva histórica de la taxonomía.](informe_files/figure-html/fig-e14-umap-producto-output-1.png){#fig-e14-umap-producto width=918 height=698}\n:::\n:::\n\n\nR1 produce grupos más alineados con Product/Issue que el control R0, pero con una\ncontrapartida importante: entre 30% y 41% queda como ruido y aparecen 120–130 clusters,\nmuchos más que las 25–40 categorías operativas buscadas. Por eso E14 **no descubre la\ntaxonomía final**; proporciona subtemas para consolidación manual.\n\n### Estabilidad y atajo por empresa\n\n| family       | run_a                 | run_b                   |   n_hashes |   n_shared_non_noise |   ari_with_noise |   ari_shared_non_noise |\n|:-------------|:----------------------|:------------------------|-----------:|---------------------:|-----------------:|-----------------------:|\n| umap_seeds   | r1_umap_seed42_mcs100 | r1_umap_seed43_mcs100   |      73512 |                47242 |           0.7257 |                 0.9711 |\n| umap_seeds   | r1_umap_seed42_mcs100 | r1_umap_seed44_mcs100   |      73512 |                48599 |           0.7865 |                 0.9914 |\n| umap_seeds   | r1_umap_seed43_mcs100 | r1_umap_seed44_mcs100   |      73512 |                47097 |           0.739  |                 0.9767 |\n| company_mask | r1_umap_seed42_mcs100 | r1_masked_seed42_mcs100 |      73512 |                40708 |           0.4858 |                 0.8563 |\n| metric                       |       value |\n|:-----------------------------|------------:|\n| train_event_rows             | 100000      |\n| train_unique_hashes          |  73512      |\n| hashes_with_product_conflict |    452      |\n| hashes_with_issue_conflict   |    595      |\n| texts_changed_by_mask        |   9688      |\n| pct_texts_changed            |     13.1788 |\n| changed_reused_from_r1       |      0      |\n| new_masked_texts_encoded     |   9686      |\n| unique_masked_hashes         |  73510      |\n| hashes_merged_after_mask     |      2      |\n\n\nEntre semillas, el ARI sobre hashes no-ruido está entre 0.971 y 0.991: la estructura central\nes estable, mientras la principal variación está en qué textos HDBSCAN declara ruido. El\nenmascarado modificó 9,688 textos (13.18%), aumentó el ruido de 30.1% a 40.7% y produjo un\nARI 0.856 sobre los hashes no-ruido compartidos. La empresa influye, pero no explica por sí\nsola la estructura semántica.\n\n::: {#cell-fig-e14-company-mask .cell execution_count=52}\n\n::: {.cell-output .cell-output-display}\n![UMAP 2D antes y después de ocultar aliases de empresa. Naranja identifica los mismos textos cuyo contenido sí cambió por el enmascarado.](informe_files/figure-html/fig-e14-company-mask-output-1.png){#fig-e14-company-mask width=1093 height=509}\n:::\n:::\n\n\nLos dos UMAP se ajustan independientemente; sus ejes pueden rotar o desplazarse y por eso no\nse comparan coordenadas punto a punto. La evidencia cuantitativa del cambio es el ARI y la\ntasa de ruido reportados arriba.\n\n### Topics c-TF-IDF\n\n::: {#cell-fig-e14-topics .cell execution_count=53}\n\n::: {.cell-output .cell-output-display}\n![Ocho clusters originales con más narrativas únicas. Las etiquetas muestran sus tres términos c-TF-IDF principales.](informe_files/figure-html/fig-e14-topics-output-1.png){#fig-e14-topics width=1220 height=494}\n:::\n:::\n\n\n| condition      |   cluster |   n_hashes | top_terms                                                                                                                                      | top_product                                         | representative_excerpt                                                                                          |\n|:---------------|----------:|-----------:|:-----------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------|:----------------------------------------------------------------------------------------------------------------|\n| company_masked |        96 |       3639 | inquiries | inquiry | xxxx xxxx | xxxx | unauthorized | xx | credit | credit report | xx xx | unauthorized inquiries                           | Credit reporting or other personal consumer reports | i urge you to act swiftly in removing these unauthorized inquiries from my credit report. they are causing sig… |\n| company_masked |       100 |       3318 | accounts | fraudulent | identity | theft | identity theft | fraudulent accounts | report | credit report | credit | account                    | Credit reporting or other personal consumer reports | several accounts appear on my credit report without my consent and are incorrect. please remove these fraudule… |\n| company_masked |       106 |       1603 | fcra | account | credit | inaccurate | date | reported | status | reporting | information | credit report                                      | Credit reporting or other personal consumer reports | xxxx xxxxxxxx xxxx xxxx xxxx xxxxxxxx xxxx xxxx xxxxxxxx xxxx xxxxxxxx date of birth : xx/xx/xxxx ss # : xxxx … |\n| company_masked |       126 |       1237 | loans | loan | student | student loan | company | student loans | payments | forbearance | xx | school                                         | Student loan                                        | i filed a complaint against xxxx based upon their fraudulent and deceptive practices. the department of educat… |\n| company_masked |       129 |       1007 | bank | funds | money | check | told | account | transfer | company | called | deposit                                                          | Checking or savings account                         | in early xxxx i opened an account for my small business with truist bank. i deposit our checks daily through a… |\n| company_masked |        84 |        994 | opt | consumer | financial institution | institution | financial | exercise | personal information | nonpublic | personal | nonpublic personal | Credit reporting or other personal consumer reports | under the fair credit reporting act ( fcra ), as delineated in 15 usc 1681, consumer reporting agencies, namel… |\n| unmasked       |        83 |       6186 | debt | collection | validation | company | alleged | debt collection | collector | original | collect | alleged debt                           | Debt collection                                     | xx/xx/year>2024 progressive management systems xxxx xxxx xxxx xxxx xxxx xxxx ca, xxxx re : debt validation req… |\n| unmasked       |        60 |       3894 | inquiries | xxxx xxxx | inquiry | xxxx | unauthorized | xx | xx xx | xxxx xx | xx xxxx | credit                                                | Credit reporting or other personal consumer reports | i urge you to act swiftly in removing these unauthorized inquiries from my credit report. they are causing sig… |\n| unmasked       |        94 |       3427 | accounts | fraudulent | identity | theft | identity theft | report | fraudulent accounts | credit report | credit | account                    | Credit reporting or other personal consumer reports | several accounts appear on my credit report without my consent and are incorrect. please remove these fraudule… |\n| unmasked       |       100 |       2584 | late | payments | late payment | late payments | payment | credit | inaccurate late | reported | time | reporting                              | Credit reporting or other personal consumer reports | i recently reviewed my consumer report and discovered an erroneous late payment entry on an account where i ha… |\n| unmasked       |        99 |       1965 | fcra | credit | account | inaccurate | reporting | date | information | credit report | report | reported                                      | Credit reporting or other personal consumer reports | xxxx xxxxxxxx xxxx xxxx xxxx xxxxxxxx xxxx xxxx xxxxxxxx xxxx xxxxxxxx date of birth : xx/xx/xxxx ss # : xxxx … |\n| unmasked       |       120 |       1584 | bank | money | bank america | america | funds | check | told | account | xx | called                                                           | Checking or savings account                         | on xx/xx/23, i awoke from sleep after working night shift to a text message about verifying repeated failed lo… |\n\n\nLos términos recuperan subtemas reconocibles —deuda no reconocida, consultas no autorizadas,\nrobo de identidad y pagos tardíos—, pero también tokens de enmascarado como `xxxx`. Esa\ncontaminación debe tratarse en la limpieza léxica antes de considerar `topic_id` como feature.\n\n## Cierre de CRISP-DM 2 — Comprensión de los Datos {#sec-cierre-crisp2}\n\nLa etapa se considera **completada** porque E1-E14 ya tienen método, parámetros, artefactos y\nconclusión reproducible. Quedan congeladas estas decisiones para pasar a Preparación:\n\n- régimen principal 2023-2025 y 2026 como OOD;\n- contrato anti-fuga F0/F1/FX;\n- hash normalizado y doble vista operacional/purgada;\n- R0 TF-IDF como representación predictiva principal;\n- R1 reservado para topics, recuperación y challengers, no como feature global por defecto;\n- E14 como evidencia para revisión humana, no como taxonomía automática.\n\nQue el tipado completo ya exista no contradice CRISP-DM: fue infraestructura mínima adelantada\ny marca el inicio iterativo de la etapa 3. Desde este punto no se añaden nuevos experimentos\nde comprensión; el trabajo continúa con taxonomía, hashes/splits completos y features finales.\n\n## Preparación CRISP-DM — Fases técnicas 2-5 {#sec-features}\n\nEl Informe I documenta cada transformación con entradas, parámetros, salidas, conteos y\npruebas. La fase técnica de tipado ya procesó el corpus completo:\n\n| check                           | status   | value      | expected   |\n|:--------------------------------|:---------|:-----------|:-----------|\n| filas_preservadas               | ok       | 3837184    | 3837184    |\n| complaint_id_unico              | ok       | 3837184    | 3837184    |\n| fecha_min                       | ok       | 2015-03-19 | 2011-01-01 |\n| fecha_max                       | ok       | 2026-07-27 | 2026-12-31 |\n| columnas_salida                 | ok       | 23         | 23         |\n| memoria_raw_sin_texto_mib       | info     | 1470.59    | nan        |\n| memoria_tipado_categorico_mib   | info     | 227.22     | nan        |\n| reduccion_memoria_sin_texto_pct | ok       | 84.55      | 80.0       |\n| parquet_raw_sin_texto_mib       | info     | 54.62      | nan        |\n| parquet_tipado_sin_texto_mib    | info     | 39.96      | nan        |\n| tamano_parquet_total_mib        | info     | 750.17     | nan        |\n\n\n1. **Tipado — completo:** 3,837,184 filas, fechas, booleanos, categorías, tags separados,\n   targets y contrato de dominios; reducción de memoria no-texto de 84.55%.\n2. **Canonicalización — borrador v1 ejecutado:** mapa manual versionado de 21 productos a\n   11 y de 173 `Issue` a 33 motivos. El mapa es completo y determinista, pero debe ser\n   aprobado por negocio antes de considerarlo estable.\n3. **Repetidos — pendiente:** hash, conflictos de etiquetas y vistas operacional/texto único.\n4. **Split:** train 2023-2024, validación 2025-01/06 y test 2025-07/12; 2026 queda como\n   stress test OOD separado.\n5. **R0:** word/character TF-IDF y señales deterministas, con `fit` solo en train.\n6. **R1:** embedding local versionado, una vez por hash.\n7. **Ensamblado:** IDs/tabulares en Parquet, TF-IDF CSR en `.npz`, embeddings en `.npy` e\n   índices/manifiestos en Parquet.\n8. **Auditoría:** dimensiones, memoria, nulos, cobertura, columnas por tier y prueba que\n   prohíbe FX.\n\n### F3 — Canonicalización de Product e Issue\n\n`configs/taxonomia.yaml` enumera cada etiqueta permitida; no usa narrativa, empresa,\noutcomes ni clusters para asignar el target. Las tres familias históricas que mezclan\nproductos (`Consumer Loan`, `Credit card or prepaid card` y `Other financial service`) se\nresuelven con reglas explícitas de `Sub-product`. Una etiqueta nueva genera error en vez de\ncaer silenciosamente en `OTRO`.\n\n| dimension         |   clases |   train |   validation |   test |   ood_2026 |\n|:------------------|---------:|--------:|-------------:|-------:|-----------:|\n| motivo_canonico   |       33 | 1301794 |       695184 | 526872 |     107158 |\n| producto_canonico |       11 | 1301794 |       695184 | 526872 |     107158 |\n\n\n::: {#cell-fig-f3-taxonomia .cell execution_count=57}\n\n::: {.cell-output .cell-output-display}\n![Doce motivos canónicos con mayor soporte en train. Validación y test se muestran para verificar continuidad temporal, no para diseñar el mapa.](informe_files/figure-html/fig-f3-taxonomia-output-1.png){#fig-f3-taxonomia width=1246 height=574}\n:::\n:::\n\n\nLas 33 clases tienen soporte distinto de cero en train, validación y test. El parquet\n`canonico.parquet` conserva las 3,837,184 filas y mantiene `product`/`issue` crudos junto a\n`producto_canonico`, `motivo_canonico`, `target_t1_motivo_canonico` y la versión del mapa.\nLa tabla completa de 173 equivalencias queda en `f03_taxonomia_mapping.csv`.\n\n::: {.callout-warning appearance='simple'}\n## Pendiente — F5\n\nMatrices F0/R0/R1 y auditoría de fuga. El artefacto `f5_features.csv` todavía no existe; esta sección se completa sola al ejecutar:\n\n```bash\nuv run python -m src.features.build\n```\n:::\n\n\nDVC debe rastrear el DAG completo, no solo el parquet crudo:\n\n```{mermaid}\nflowchart TD\n    A[raw completo]\n    subgraph U[CRISP-DM 2 - Comprensión]\n        B[prepare_eda_sample]\n        C[build_tfidf]\n        D[build_embeddings]\n        E[e12_baseline]\n        F[e13_compare_representations]\n        G[prepare_e14]\n        H[e14_clustering]\n        V[e14_visualization]\n        B --> C\n        B --> D\n        C --> E\n        C --> F\n        D --> F\n        D --> G\n        C --> H\n        G --> H\n        H --> V\n    end\n    subgraph P[CRISP-DM 3 - Preparación]\n        I[type_full_corpus]\n        J[canonicalize_taxonomy]\n        K[split completo]\n        L[features R0 completas]\n        I --> J --> K --> L\n    end\n    A --> B\n    A --> I\n    F --> J\n    H --> J\n```\n\n`dvc.yaml` conserva estos mismos bloques mediante comentarios CRISP-DM. No se renombran las\netapas ya publicadas porque sus nombres forman parte del historial de `dvc.lock`.\n\nCada etapa declara código/configuración como dependencia, artefactos como salidas y semillas,\nventanas, muestra y modelo de embedding en `params.yaml`. `dvc.lock` fija los hashes que\npermiten reproducir cada tabla del informe.\n\n# El quiebre de 2026 {#sec-quiebre}\n\nAl empezar el análisis, la explicación de trabajo para las cifras raras de 2026 era la\nobvia: **censura**, es decir, reclamos recientes cuyo desenlace todavía no se ha\nregistrado. El dato descarta esa explicación y deja algo más incómodo en su lugar.\n\n**Evidencia 1 — el campo de censura está vacío.** De los 107,158 reclamos de 2026,\n**exactamente uno** aparece marcado como `In progress`. Si el problema fuera que los casos\nsiguen abiertos, ese contador sería enorme. No lo es.\n\n**Evidencia 2 — el volumen no decae, se quiebra.** Diciembre de 2025 cierra con 56,510\nreclamos y enero de 2026 con 22,211: una caída del 61% en un mes. Después el volumen se\nqueda en una meseta de entre 10 mil y 22 mil durante seis meses. Un rezago de publicación\nproduce una cola que se desvanece en los últimos uno o dos meses, no un escalón seguido de\nuna meseta estable.\n\n**Evidencia 3 — cambia la composición, no solo la cantidad.** Es el argumento decisivo. En\n2025 la familia *credit reporting* representaba el 75% de los reclamos del año; en 2026\ncae al 4%, mientras *debt collection* sube de 8% a 34% y *checking or savings account* de\n4% a 18% (@fig-deriva). Un rezago de publicación retrasa reclamos de todos los tipos por\nigual y **conserva la mezcla**. Aquí la mezcla se da vuelta por completo.\n\n**Conclusión.** Las tres piezas apuntan a lo mismo: 2026 no es 2025 con menos datos, es un\n**proceso generador distinto**. El dato por sí solo no dice por qué —eso exige verificar\nqué cambió en la operación o en la política de publicación del CFPB durante ese periodo, y\nes una pregunta abierta que el equipo debe resolver con fuentes externas, no con el\nparquet.\n\n**Consecuencia operativa, que ya se aplicó:** el régimen de entrenamiento se cierra en\n**diciembre de 2025**, y la división temporal se reacomoda íntegramente dentro de él —\nentrenamiento 2023-01 a 2024-12, validación 2025-01 a 2025-06, prueba 2025-07 a 2025-12.\nLa propuesta original usaba 2026 como periodo de prueba; hacerlo habría significado medir\nel modelo contra una distribución que no es la que verá en producción, y habría producido\nun número de evaluación pesimista y sin sentido.\n\n# Decisiones de diseño registradas {#sec-decisiones}\n\n| # | Decisión | Consecuencia |\n|---|---|---|\n| **D1** | El objetivo prometido no existe; se reemplaza por «la respuesta registró relief», declarado como *proxy* | cambia y acota la promesa de la propuesta |\n| **D1b** | Regla de etiquetado caso por caso; `In progress` y nulos se excluyen | evita ruido dirigido en la etiqueta |\n| **D2** | Contrato F0 / F1 / FX de disponibilidad temporal | ninguna columna post-respuesta puede ser variable predictora |\n| **D3** | Ventana principal restringida a 2023-2025 | 2026 no se mezcla con la métrica principal y se conserva como stress test OOD |\n| **D4** | División temporal, nunca aleatoria; prueba operacional y prueba purgada por hash en 2025-07 a 2025-12 | separa rendimiento real con plantillas recurrentes de generalización a texto nuevo |\n| **D5** | Muestra de desarrollo de 300 mil filas estratificada | itera en minutos, no en horas |\n| **D6** | R0 TF-IDF y R1 local son las únicas representaciones predictivas; el LLM queda después de T1-T4 | el agente puede cambiar sin regenerar features y no contamina la evaluación |\n\nLa justificación completa de cada una está en `docs/plan-eda-y-transformacion.md`.\n\n# Riesgos abiertos {#sec-riesgos}\n\n| Riesgo | Estado | Mitigación |\n|---|---|---|\n| El objetivo de la propuesta no existe | **confirmado** | D1: se usa un proxy y se declara como tal |\n| Empresa como atajo del modelo | **medido, no cerrado** | E14 enmascaró 13.18% de textos; subió el ruido y cambió fronteras, pero la estructura no-ruido conservó ARI 0.856 (@sec-e14) |\n| PII residual en la narrativa | **medido**, mitigación obligatoria | menos del 1% de los textos, pero no cero: segundo enmascarado antes de cualquier llamada externa (@sec-contenido) |\n| El quiebre de 2026 no tiene causa identificada | **abierto**, aislado del test principal | prueba principal en 2025-07/12 y 2026 como stress test OOD separado; falta confirmar la causa externa |\n| Fuga por columnas post-respuesta | contrato definido; prueba pendiente | F5 debe añadir una prueba automática que falle si aparece FX |\n| Memorización de plantillas | **implementada en la muestra** | hash, cache por texto, E14 unique-only y evaluación E12 operacional/purgada; falta extender hashes al corpus completo (@sec-plantillas) |\n| Deriva de etiquetas y de tasa base | cuantificado | régimen 2023+, mapa canónico versionado, prueba de regresión |\n| Sesgo por perfil del consumidor | **medido**, con un residuo abierto | la mezcla de productos explica ~4/5 de la brecha de `Older American`, pero no toda; `State` se explica casi entero (@sec-sesgo). Cortes obligatorios en la evaluación de la Fase 6 |\n\n# Próximos pasos {#sec-proximos}\n\n1. Revisar los 122 topics E14 y congelar una taxonomía manual de 25–40 motivos.\n2. Ejecutar E13 sobre las mismas filas para decidir R0, R1 o su combinación.\n3. Aplicar la taxonomía al corpus completo y construir hashes/splits completos.\n4. Regenerar la representación ganadora sobre todo train/validation/test y auditar FX.\n5. Completar F5, actualizar este informe y renderizar el entregable EDA + features.\n6. Confirmar con fuentes externas qué originó el quiebre de 2026 (@sec-quiebre); mientras\n   tanto se conserva como stress test OOD separado.\n\n# Reproducibilidad {.appendix #sec-repro}\n\nTodo el contenido de este informe se regenera desde el dato crudo con:\n\n```bash\nuv sync\ndvc pull                                 # descarga artefactos versionados\nuv run python -m src.data.profile         # E1\nuv run python -m src.data.agregados       # D1b, E2, E3, E4, E7, E8, E9\nuv run python -m src.data.narrativa       # E5, E6\nuv run python -m src.evaluation.slices    # E11\nuv run dvc repro                          # F2, R0, R1, E12 y E14 implementados\nuv run quarto render reports/informe      # este documento\n```\n\nEl informe lee exclusivamente los CSV de `reports/artefactos/`, nunca los Parquet o matrices\ngrandes. Las secciones sin artefacto se marcan como pendientes en lugar de fallar, así que\nel documento siempre compila.\n\n# Nota sobre uso de IA generativa {.appendix .unnumbered}\n\nSe utilizaron herramientas de IA generativa como apoyo en la redacción de código y de este\ndocumento. Todas las cifras presentadas se calcularon sobre el dato real mediante el\ncódigo versionado en `src/`, y son verificables ejecutando los comandos de @sec-repro. Las\ndecisiones de diseño y su justificación fueron revisadas por el equipo.\n\n",
    "supporting": [
      "informe_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}